# Generated by Django 4.0.2 on 2022-02-28 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_given_name_customer_first_name'),
    ]

    operations = []
